=== bentocorp/backend-survey/src/main/resources/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
  elementFormDefault="qualified"
  targetNamespace="http://resource.bentonow.com/survey/config.xsd"
  xmlns:cf="http://resource.bentonow.com/survey/config.xsd"
  xmlns:dt="http://commons.safris.org/datatypes.xsd"
  xmlns:dbcp="http://commons.safris.org/dbcp.xsd"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:import namespace="http://commons.safris.org/datatypes.xsd" schemaLocation="http://commons.safris.org/datatypes.xsd"/>
  <xs:import namespace="http://commons.safris.org/dbcp.xsd" schemaLocation="http://commons.safris.org/dbcp.xsd"/>
  
  <xs:simpleType name="port">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="35535"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="server" abstract="true">
    <xs:attribute name="host" type="xs:token"/>
    <xs:attribute name="port" type="cf:port" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="http">
    <xs:complexContent>
      <xs:extension base="cf:server"/>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="https">
    <xs:complexContent>
      <xs:extension base="cf:server">
        <xs:sequence>
          <xs:element name="keystore">
            <xs:complexType>
              <xs:attribute name="path" type="xs:token" use="required"/>
              <xs:attribute name="password" type="xs:token" use="required"/>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="mail">
    <xs:all>
      <xs:element name="server">
        <xs:complexType>
          <xs:all>
            <xs:element name="credentials">
              <xs:complexType>
                <xs:attribute name="username" type="xs:string" use="required"/>
                <xs:attribute name="password" type="xs:string" use="required"/>
              </xs:complexType>
            </xs:element>
          </xs:all>
          <xs:attribute name="host" type="xs:token" use="required"/>
          <xs:attribute name="port" type="cf:port" use="required"/>
          <xs:attribute name="protocol" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:NCName">
                <xs:enumeration value="smtp"/>
                <xs:enumeration value="smtps"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:complexType>
      </xs:element>
      <xs:element name="message">
        <xs:complexType>
          <xs:all minOccurs="0">
            <xs:element name="override">
              <xs:complexType>
                <xs:attribute name="to" use="required">
                  <xs:simpleType>
                    <xs:list itemType="dt:email"/>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
          </xs:all>
          <xs:attribute name="from" type="dt:email" use="required"/>
          <xs:attribute name="subject" type="xs:string" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>
  
  <xs:complexType abstract="true" name="execute"/>
  
  <xs:complexType abstract="true" name="everyTimeZone">
    <xs:complexContent>
      <xs:extension base="cf:execute">
        <xs:attribute name="timeZone" type="dt:javaTimeZone" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="seconds">
    <xs:complexContent>
      <xs:extension base="cf:execute">
        <xs:attribute name="every" use="required">
          <xs:annotation>
            <xs:documentation>[1,60]</xs:documentation>
          </xs:annotation>
          <xs:simpleType>
            <xs:restriction base="xs:int">
              <xs:minInclusive value="1"/>
              <xs:maxInclusive value="60"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="minutes">
    <xs:complexContent>
      <xs:extension base="cf:execute">
        <xs:attribute name="every" use="required">
          <xs:annotation>
            <xs:documentation>[1,60]</xs:documentation>
          </xs:annotation>
          <xs:simpleType>
            <xs:restriction base="xs:int">
              <xs:minInclusive value="1"/>
              <xs:maxInclusive value="60"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="begin" use="required">
          <xs:annotation>
            <xs:documentation>ss</xs:documentation>
          </xs:annotation>
          <xs:simpleType>
            <xs:restriction base="xs:int">
              <xs:minInclusive value="0"/>
              <xs:maxInclusive value="59"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="hours">
    <xs:complexContent>
      <xs:extension base="cf:everyTimeZone">
        <xs:attribute name="every" use="required">
          <xs:annotation>
            <xs:documentation>[1,24]</xs:documentation>
          </xs:annotation>
          <xs:simpleType>
            <xs:restriction base="xs:int">
              <xs:minInclusive value="1"/>
              <xs:maxInclusive value="24"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="begin" use="required">
          <xs:annotation>
            <xs:documentation>mm:ss</xs:documentation>
          </xs:annotation>
          <xs:simpleType>
            <xs:restriction base="xs:token">
              <xs:pattern value="(([0-9])|([01][0-9])|(2[0-4])):(([0-9])|([0-5][0-9]))"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="days">
    <xs:complexContent>
      <xs:extension base="cf:everyTimeZone">
        <xs:attribute name="every" use="required">
          <xs:annotation>
            <xs:documentation>[1,7]</xs:documentation>
          </xs:annotation>
          <xs:simpleType>
            <xs:restriction base="xs:int">
              <xs:minInclusive value="1"/>
              <xs:maxInclusive value="7"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="begin" use="required" type="xs:time">
          <xs:annotation>
            <xs:documentation>hh:mm:ss</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="minutesBeforeNow">
    <xs:attribute name="minutesBeforeNow" type="xs:nonNegativeInteger" use="required"/>
  </xs:complexType>

  <xs:complexType name="parameters">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="parameter">
        <xs:complexType>
          <xs:attribute name="name" type="xs:NCName" use="required"/>
          <xs:attribute name="value" type="xs:token" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="webApi">
    <xs:all>
      <xs:element name="parameters" type="cf:parameters" minOccurs="0"/>
    </xs:all>
  </xs:complexType>
  
  <xs:complexType name="worker">
    <xs:all>
      <xs:element name="match">
        <xs:complexType>
          <xs:all>
            <xs:element name="start" type="cf:minutesBeforeNow"/>
            <xs:element name="end" type="cf:minutesBeforeNow"/>
          </xs:all>
          <xs:attribute name="field" fixed="createdOn" use="required"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="execute" type="cf:execute"/>
    </xs:all>
  </xs:complexType>
  
  <xs:simpleType name="loggingLevel">
    <xs:restriction base="xs:token">
      <xs:enumeration value="OFF"/>
      <xs:enumeration value="SEVERE"/>
      <xs:enumeration value="WARNING"/>
      <xs:enumeration value="INFO"/>
      <xs:enumeration value="FINE"/>
      <xs:enumeration value="FINER"/>
      <xs:enumeration value="FINEST"/>
      <xs:enumeration value="ALL"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="logging">
    <xs:attribute name="name" type="xs:NCName" use="required"/>
    <xs:attribute name="level" type="cf:loggingLevel" use="required"/>
  </xs:complexType>
  
  <xs:element name="config">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="debug" minOccurs="0">
          <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
              <xs:element name="logging">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="logger" type="cf:logging" minOccurs="0" maxOccurs="unbounded"/>
                  </xs:sequence>
                  <xs:attribute name="global" type="cf:loggingLevel" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="externalResourcesAccess" type="xs:boolean" default="false"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="server" type="cf:server"/>
        <xs:element name="admin">
          <xs:complexType>
            <xs:all>
              <xs:element name="credentials">
                <xs:complexType>
                  <xs:attribute name="username" type="xs:string" use="required"/>
                  <xs:attribute name="password" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:all>
          </xs:complexType>
        </xs:element>
        <xs:element name="webApi" type="cf:webApi"/>
        <xs:element name="worker" type="cf:worker"/>
        <xs:element name="mail" type="cf:mail"/>
        <xs:element ref="dbcp:dbcp"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== bentocorp/backend-survey/src/main/resources/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config
  xmlns="http://resource.bentonow.com/survey/config.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://resource.bentonow.com/survey/config.xsd config.xsd">
  
  <debug externalResourcesAccess="true">
    <logging global="FINER"/>
  </debug>
  
  <server host="localhost" port="8080">
    <webApi>
      <parameter name="api_username" value="seva_kjHgbmAq*7%40%235_%25KLbH"/>
      <parameter name="api_password" value="%245y%2410%24Ldvko.Fby1IhGHl16njuLOIbWlwz9TvMbBjqrph%2FlJuYIQxqTMyuG.86"/>
    </webApi>
  </server>
  
  <admin>
    <credentials username="admin" password="admin"/>
  </admin>
  
  <match>
    <createdOn>
      <start minutesBeforeNow="3500"/>
      <end minutesBeforeNow="60"/>
    </createdOn>
  </match>
  
  <worker>
    <execute every="10" xsi:type="seconds"/>
  </worker>
  
  <mail>
    <server host="smtp.mailgun.org" port="465" protocol="SMTPS">
      <credentials username="postmaster@mg.bentonow.com" password="45ca46a82cd8b6e3ae4873bcb03c0cad"/>
      <email from="noreply@bentonow.com" subject="Bento Experience Survey"/>
    </server>
    <!--<server host="smtp.safris.com" port="465" protocol="SMTP">
      <credentials username="filehost" password="FileH0st"/>
      <email from="noreply@bentonow.com" subject="Bento Experience Survey"/>
    </server>-->
  </mail>
  
</config>
